package_name: android-eclipse
version: 0.1
license: MIT
authors: [Michal Srb <msrb_at_redhat.com>]
homepage: https://github.com/msrb/devassistant-assistants-fedora
summary: Assistant for setting up Android development environment in Eclipse
bugreports: https://github.com/msrb/devassistant-assistants-fedora/issues
